// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfcDwO36Ct9aijCyT2bv1p2RPfFzG8Jps',
    appId: '1:316317586609:web:f89bbb3e10726a26ecbe90',
    messagingSenderId: '316317586609',
    projectId: 'flashlango-2000',
    authDomain: 'flashlango-2000.firebaseapp.com',
    storageBucket: 'flashlango-2000.firebasestorage.app',
    measurementId: 'G-0SXBHQE14T',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANRruffHcyp8h1hTLvxF1yZhFntAPyUbU',
    appId: '1:316317586609:ios:dbada16f3a434115ecbe90',
    messagingSenderId: '316317586609',
    projectId: 'flashlango-2000',
    storageBucket: 'flashlango-2000.firebasestorage.app',
    iosBundleId: 'com.example.flashlingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfcDwO36Ct9aijCyT2bv1p2RPfFzG8Jps',
    appId: '1:316317586609:web:6ff51de15b49d959ecbe90',
    messagingSenderId: '316317586609',
    projectId: 'flashlango-2000',
    authDomain: 'flashlango-2000.firebaseapp.com',
    storageBucket: 'flashlango-2000.firebasestorage.app',
    measurementId: 'G-PZ0WD5EB4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyComwKcilDT-gE9IpuEMXYVjahYLlkKmaQ',
    appId: '1:316317586609:android:8fbbf96500a2ff94ecbe90',
    messagingSenderId: '316317586609',
    projectId: 'flashlango-2000',
    storageBucket: 'flashlango-2000.firebasestorage.app',
  );

}